apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qc7lg9ino-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qc7lg9ino-go 
  name: qc7lg9ino-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qc7lg9ino-go 
